FROM mcr.microsoft.com/deployment-environments/runners/core:latest

RUN wget -O terraform.zip https://releases.hashicorp.com/terraform/1.7.4/terraform_1.5.5_linux_amd64.zip \
    && unzip terraform.zip && rm terraform.zip \
    && mv terraform /usr/bin/terraform
